// <auto-generated />
using System;
using CreateShortLink.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreateShortLink.Migrations
{
    [DbContext(typeof(ModelDbContext))]
    [Migration("20230201151405_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreateShortLink.Models.Entity.Longlink", b =>
                {
                    b.Property<Guid>("Longlinkid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LongLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Longlinkid");

                    b.ToTable("Linkssss");
                });

            modelBuilder.Entity("CreateShortLink.Models.Entity.ShortLink", b =>
                {
                    b.Property<Guid>("ShortLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("ShortLinkId");

                    b.ToTable("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
